name: Manually triggered release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Please provie version you want to release'
        required: true
  pull_request:
    branches:
      - 'main'

jobs:
  release_job:
    runs-on: macos-11
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        submodules: true
    - name: Print parameters
      run: |
        echo "Running release ${{ github.event_name }}!"
        echo "version: ${{ github.event.inputs.version }}!"
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Print parameters
      run: |
        bundle exec fastlane release version:${{ github.event.inputs.version }}
