name: Manually triggered release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Please provide the version you want to release'
        default: '1.0.0'
        required: true
  pull_request:
    branches:
      - 'aj/release_test'

jobs:
  release_job:
    environment:  release_approval
    runs-on: macos-11
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        submodules: true
    - name: Setup git user
      run: |
          git config --global user.name "Artur Jankowski"
          git config --global user.email "ajankowski@box.com"
    - name: Print parameters
      run: |
        echo "Running release ${{ github.event_name }}!"
        echo "version: ${{ github.event.inputs.version }}!"
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Run fastlane release script
      run: |
        bundle exec fastlane ios release version:${{ github.event.inputs.version }} github_token:${{ secrets.RELEASE_TOKEN }} release_branch: ${{ github.ref_name }} is_draft:true
