name: Manually triggered release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Please provide the version you want to release'
        required: true
      git_user_name:
        description: 'Please provide git user.name'
        required: false
        default: 'Artur Jankowski'
      git_user_email:
        description: 'Please provide a git user.email'
        required: false
        default: 'ajankowski@box.com'
  pull_request:
    branches:
      - 'main'

jobs:
  release_job:
    runs-on: macos-11
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        submodules: true
    - name: Setup git user
      run: |
          git config --global user.name "${{ github.event.inputs.git_user_name }}"
          git config --global user.email "${{ github.event.inputs.git_user_email }}"
# git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
# git config --global user.email "$(git -#-no-pager log --format=format:'%ae' -n 1)"
    - name: Print parameters
      run: |
        echo "Running release ${{ github.event_name }}!"
        echo "version: ${{ github.event.inputs.version }}!"
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Run fastlane release script
      run: |
        bundle exec fastlane ios release version:${{ github.event.inputs.version }} github_token:${{ secrets.RELEASE_TOKEN }}
