name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Please provie version you want to release'
        required: true
  pull_request:
    branches:
      - 'main'

jobs:
  say_hello:
    runs-on: macos-11
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        submodules: true
    - name: step hello
      run: |
        echo "Running event ${{ github.event_name }}!"
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"