name: spell-check-lint
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
jobs:
  lint-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - name: Print path
        shell: bash
        run: pwd
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          ref: refs/heads/main
          repository: box/box-sdk-spellchecker
          # token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT


      # - name: Verify pull request title
      #   uses: arjankowski/pull_request_lint@v1.0.0
      #   with:
      #     spelling-list: 'biedronka'q